
name: reco
description: RECO Pro Interactive Hotspots
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.0.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^3.0.0
  provider: ^6.0.5
  url_launcher: ^6.1.10
  google_mobile_ads: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
